export const maleClothing = [
    "A relaxed-fit cream linen shirt with the top two buttons undone, paired with tailored olive green chinos and minimalist leather sandals.",
    "A classic navy blue polo shirt tucked into light grey slim-fit trousers, completed with clean white sneakers for a sharp, modern look.",
    "A soft, lightweight knit sweater in a heather grey color, layered over a crisp white collared shirt, paired with dark wash straight-leg denim and suede desert boots.",
    "A short-sleeve button-up shirt with a subtle bohemian pattern, worn with comfortable beige cotton-linen blend trousers and loafers.",
    "A smart casual look featuring a light blue chambray shirt with rolled-up sleeves, dark khaki chinos, and brown leather derby shoes.",
    "A monochrome outfit with a black mandarin collar shirt made of a soft fabric, paired with slim-fit black trousers and black leather Chelsea boots.",
    "A cozy yet stylish ensemble with a textured oatmeal-colored Henley shirt, comfortable dark brown corduroy pants, and sturdy walking shoes.",
    "A modern urban style with a well-fitted black turtleneck sweater, paired with charcoal grey wool trousers and clean, minimalist black sneakers.",
    "A light brown suede bomber jacket over a simple white t-shirt, paired with black slim-fit jeans and stylish boots.",
    "A casual yet put-together look with a vertical striped short-sleeve resort shirt, white linen shorts, and comfortable espadrilles.",
    "An oversized, heavy-knit cardigan in a forest green color, worn over a plain cream t-shirt and relaxed-fit light-wash jeans.",
    "A tailored single-breasted blazer in a soft beige color, worn casually over a white crew-neck t-shirt and dark trousers.",
    "A light grey shacket (shirt-jacket) layered over a classic white t-shirt, paired with slim-fit black trousers and leather sneakers.",
    "An urban streetwear look featuring a black utility vest over a muted green hoodie, paired with tapered black cargo pants and high-top sneakers.",
    "A sophisticated knit polo sweater in a camel color, worn with pleated, relaxed-fit navy trousers and brown loafers for a modern smart-casual vibe.",
    "An open flannel shirt with an earth-tone plaid pattern, layered over an oversized graphic band t-shirt, paired with straight-leg light-wash jeans.",
    "A minimalist monochrome outfit with a black technical fabric jacket, slim-fit cargo pants, and sleek black running sneakers.",
    "A relaxed, resort-style band-collar linen shirt worn open over a white tank top, paired with comfortable drawstring linen trousers and espadrilles.",
    "A soft moss green crewneck sweatshirt paired with stylish beige corduroy trousers and classic white sneakers for a clean, preppy look.",
    "A layered autumn ensemble with a dark teal turtleneck under a charcoal wool overshirt, combined with dark wash denim and boots.",
    "A relaxed vibe with light-wash straight-leg jeans, a half-tucked vintage-style t-shirt, and a simple brown leather belt.",
    "A modern classic look featuring a structured navy blue bomber jacket over a grey merino wool sweater, paired with dark grey chinos and clean white shoes.",
    "A modern batik shirt with a subtle geometric pattern, paired with slim-fit black trousers and leather slip-ons for a smart event.",
    "A lightweight, short-sleeve 'baju koko' inspired shirt with a modern minimalist design, paired with comfortable cream cotton trousers.",
    "A resort-style shirt with a vibrant tropical leaf print, worn with white linen trousers and classic leather slides.",
    "A loose-fitting rayon shirt in a solid pastel color, paired with relaxed drawstring trousers and open-toe sandals for a beachy feel.",
    "A handwoven 'tenun' overshirt worn open over a plain black t-shirt, combined with slim-fit black jeans for an ethnic-modern look.",
    "A light brown safari-style overshirt with chest pockets, paired with cream chinos and suede desert boots.",
    "A simple dark grey t-shirt paired with modern jogger pants in a subtle batik print, finished with clean white sneakers.",
    "A smart quarter-zip sweater in navy blue, layered over a crisp white collared shirt and paired with grey corduroy pants.",
    "A black nylon coach jacket over a plain white tee, paired with trendy parachute pants and chunky sneakers.",
    "An oversized, washed-black band t-shirt, worn with wide-leg carpenter jeans and retro basketball sneakers for a 90s inspired look.",
    "A technical anorak jacket in a bright color, paired with black joggers, a beanie, and trail running shoes for a gorpcore aesthetic.",
    "A tie-dye sweatshirt in muted tones, combined with ripped black denim jeans and a bucket hat for a casual, trendy style.",
    "A vertical stripe short-sleeve button-down shirt made of soft viscose, paired with tailored linen trousers and comfortable sandals.",
    "A classic crewneck sweatshirt in heather grey, worn with relaxed-fit indigo jeans, a baseball cap, and timeless sneakers.",
    "A waffle-knit Henley shirt in an off-white color, paired with comfortable olive green joggers and minimalist slip-on shoes.",
    "A classic polo shirt in a burgundy color, tucked into light-colored slim-fit chinos and worn with boat shoes.",
    "A checked flannel shirt in red and black, worn unbuttoned over a white graphic tee, paired with dark, straight-leg jeans and work boots.",
    "A Breton striped long-sleeve shirt, combined with beige trousers and comfortable espadrilles for a nautical-inspired look.",
    "A high-quality V-neck t-shirt in a deep charcoal grey, paired with slim-fit black trousers and minimalist white leather sneakers for a sharp, clean look.",
    "Pleated charcoal grey wool trousers paired with a fine-gauge merino wool sweater in a forest green color, and classic derby shoes.",
    "A light blue chambray shirt, left untucked over dark olive chinos, paired with casual brown leather loafers.",
    "A soft, unstructured knit cardigan that mimics a blazer, layered over a white henley and slim dark blue jeans.",
    "A black stand-collar (Mandarin collar) shirt made of a textured fabric, paired with grey tailored trousers and black chelsea boots.",
    "A long-sleeve knit polo in a deep wine color, paired with smart joggers in black and clean, minimalist sneakers.",
    "A technical gilet with multiple pockets layered over a long-sleeve graphic tee, paired with technical track pants.",
    "A graphic hoodie featuring abstract art, paired with slightly distressed light-wash denim and colorful, statement sneakers.",
    "A cream-colored cable-knit sweater, paired with dark brown straight-leg trousers and classic leather shoes.",
    "A simple black crew-neck t-shirt made from premium cotton, paired with tailored light grey trousers and sleek black loafers.",
      "A soft beige oversized hoodie paired with slim black jogger pants and crisp white sneakers for a relaxed weekend look.",
  "A muted olive utility overshirt worn open over a simple white tee, combined with relaxed navy chinos and suede slip-ons.",
  "A cream waffle-knit sweater paired with tapered khaki pants and canvas sneakers, giving a clean minimalist vibe.",
  "A relaxed striped linen button-up shirt in pale blue, worn untucked with beige drawstring trousers and leather sandals.",
  "A dusty brown bomber jacket layered over a grey henley shirt, paired with dark denim and classic sneakers.",
  "A light sage green crewneck sweatshirt paired with soft grey joggers and neutral running shoes for athleisure comfort.",
  "A short-sleeve Cuban collar shirt in a soft floral print, tucked into cream cotton trousers with leather slides.",
  "A modern black quarter-zip pullover paired with slim olive jogger pants and monochrome sneakers.",
  "A washed denim overshirt worn open over a plain cream tee, combined with tan chinos and casual loafers.",
  "A charcoal knit long-sleeve polo tucked into beige drawstring trousers with white sneakers for a smart casual edge.",
  "A muted terracotta lightweight hoodie paired with dark olive chinos and clean neutral trainers.",
  "A soft ivory oversized sweatshirt with dropped shoulders, combined with relaxed light khaki trousers and slip-on sneakers.",
  "A navy cotton popover shirt with band collar, styled with slim beige chinos and brown moccasins.",
  "A lightweight khaki field jacket layered over a striped tee, paired with relaxed blue jeans and desert boots.",
  "A sage green ribbed henley shirt tucked into cream tapered trousers, completed with low-top white sneakers.",
  "A pastel lavender crewneck knit paired with charcoal joggers and muted grey sneakers.",
  "A short-sleeve viscose shirt with abstract prints, worn with soft cream linen trousers and casual sandals.",
  "A muted stone-grey cardigan layered over a black t-shirt, styled with dark tapered jeans and boots.",
  "A taupe lightweight sweatshirt paired with soft navy track pants and sporty sneakers.",
  "A dusty teal knit pullover worn with ecru chinos and tan loafers for an effortless look.",
  "A light sand utility vest over a cream tee, combined with olive relaxed-fit cargo pants and sneakers.",
  "A sky-blue buttonless pullover shirt with rolled sleeves, paired with beige drawstring trousers.",
  "A charcoal grey hoodie worn under a navy overshirt, combined with slim-fit cargo pants and high-top sneakers.",
  "A cream ribbed sweater vest layered over a long-sleeve white tee, styled with brown corduroy trousers.",
  "A pastel mint lightweight crewneck sweater paired with slim charcoal chinos and low-profile sneakers.",
  "A loose rayon shirt in muted ochre, worn with beige wide-leg trousers and leather sandals.",
  "A terracotta knit hoodie paired with relaxed cream cargo pants and slip-on trainers.",
  "A light indigo chambray pullover with band collar, styled with olive drawstring trousers and sandals.",
  "A muted brown corduroy overshirt worn with an ivory tee and soft khaki chinos.",
  "A pastel peach oversized t-shirt tucked into tapered grey trousers, paired with canvas sneakers.",
  "A steel blue sweatshirt paired with beige linen trousers and neutral espadrilles.",
  "A deep forest green henley shirt tucked into ecru drawstring pants with loafers.",
  "A light grey oversized tee paired with dark olive joggers and chunky sneakers.",
  "A sand-beige knit pullover with mock neck, styled with cream relaxed trousers and suede loafers.",
  "A navy Breton striped tee tucked into muted khaki chinos with white sneakers.",
  "A sage utility overshirt paired with tan drawstring trousers and minimalist trainers.",
  "A maroon crewneck sweatshirt with ribbed cuffs, worn with black tapered cargo pants and sneakers.",
  "A muted beige polo knit tucked into cream pleated trousers with brown sandals.",
  "A vintage-inspired washed indigo denim jacket layered over a striped tee, paired with chinos.",
  "A pastel seafoam crewneck sweater styled with soft grey joggers and slip-ons.",
  "A soft camel hoodie paired with dark olive chinos and neutral sneakers.",
  "A dusty plum ribbed henley tucked into beige linen trousers with sandals.",
  "A muted teal sweatshirt worn with off-white relaxed cargo pants and boots.",
  "A relaxed cream utility overshirt paired with brown drawstring trousers and white sneakers.",
  "A pastel blue crewneck t-shirt tucked into ecru tapered chinos with leather loafers.",
  "A moss green knitted pullover styled with soft grey joggers and casual slip-ons.",
  "A sand-colored crewneck tee with boxy fit, worn with loose-fit light denim jeans.",
  "A charcoal pullover hoodie paired with olive cargo trousers and sneakers.",

];

export const femaleClothingHijab = [
    "An airy, long-sleeved sage green blouse with structured puff sleeves, tucked into high-waisted cream palazzo pants. The look is completed with a matching soft sage pashmina hijab styled elegantly.",
    "A contemporary co-ord set featuring an asymmetric tunic and matching wide-leg trousers in a soft terracotta color, complemented by a neutral beige chiffon hijab.",
    "A stylish layered look with a draped, sleeveless waterfall vest in deep navy blue over a simple white long-sleeved top, paired with tailored white wide-leg trousers and a light blue satin hijab.",
    "A bohemian-inspired outfit featuring a tiered maxi skirt in a subtle earth-tone print, cinched with a thin tan belt, paired with a fitted cream long-sleeved top. A soft brown jersey hijab is loosely draped.",
    "An elegant ensemble consisting of a blush pink long-sleeved peplum blouse with subtle bishop sleeves, paired with classic white wide-leg trousers. A matching blush pink georgette hijab adds a touch of grace.",
    "A fashionable outfit with a long, belted shirt tunic in a subtle geometric print, worn open at the bottom over slim-fit white pants. The hijab is a solid color from the print, creating a cohesive look.",
    "A sophisticated and minimalist look with a lightweight, ankle-length duster coat in a neutral tone, worn open over a simple cream top and matching trousers. A silk hijab in a similar shade completes the elegant monochrome style.",
    "A smart casual outfit featuring a stylish long-sleeved blouse in a muted floral print, paired with chic dusty rose colored culottes. The hijab is a solid dusty rose to match.",
    "A trendy outfit with an oversized denim jacket over a white long-sleeved top, paired with a pleated A-line maxi skirt in a pastel color. The hijab is a soft neutral color to balance the look.",
    "A graceful and flowing pale lilac blouse with delicate bishop sleeves, tucked into high-waisted, wide-leg trousers in a deep plum color. A matching lilac chiffon hijab is elegantly wrapped.",
    "A minimalist chic look with a long, sleeveless knit dress in a camel color, layered over a crisp white long-sleeved shirt. The hijab is a matching camel color for a monochrome effect.",
    "An architectural look featuring an oversized, crisp white poplin shirt with dramatic cuffs, half-tucked into belted, straight-leg vegan leather trousers in a deep olive color. A simple black modal hijab keeps the focus on the silhouette.",
    "A casual chic look with an oversized white poplin shirt, half-tucked into high-waisted wide-leg blue jeans, paired with a vibrant satin hijab for a pop of color.",
    "A cozy and elegant outfit featuring a chocolate brown satin maxi skirt paired with a chunky cream-colored knit sweater, complemented by a neutral pashmina hijab.",
    "A modern layered look with a long, sleeveless knit vest in beige over a simple long-sleeved white maxi dress, styled with a matching beige chiffon hijab.",
    "A bold coordinated set in emerald green, consisting of a modest-cut long-sleeved top and matching high-waisted palazzo pants, paired with a simple black hijab.",
    "A timeless city look with a classic beige trench coat worn over a black turtleneck top and black straight-leg trousers, completed with an elegant black silk hijab.",
    "A soft, feminine outfit with a flowy tunic featuring bell sleeves in a pastel floral print, paired perfectly with white culottes and a matching pastel hijab.",
    "A modern utility style featuring a khaki-colored long shirt-dress, belted at the waist, worn open from the knee down over straight-leg ecru jeans.",
    "An athleisure chic monochrome outfit with a light grey long-sleeved ribbed top, smart heather grey wide-leg trousers, and a matching light grey jersey hijab.",
    "An elegant look with a dusty blue pleated chiffon maxi skirt, paired with a simple tucked-in white long-sleeved blouse and a crisp white hijab.",
    "A contemporary outfit featuring a dark wash denim maxi dress with a full button-front and long cuffed sleeves, cinched with a statement tan leather belt.",
    "A monochrome set with a relaxed-fit linen button-up shirt and matching wide-leg trousers in a soft beige color. A slightly darker beige hijab adds subtle depth.",
    "An elegant A-line satin maxi skirt in dusty rose, perfectly matched with a fine-knit cream turtleneck sweater. A dusty rose chiffon hijab completes the look.",
    "A trendy denim-on-denim look featuring a long, light-wash denim overshirt worn above a white top, paired with matching straight-leg jeans. A simple white hijab keeps it fresh.",
    "A classic combination of a crisp white oversized poplin shirt, partially tucked into a flowy navy blue pleated maxi skirt. The look is unified with a matching navy hijab.",
    "An earth-toned utility outfit with a khaki long-sleeved shirt featuring chest pockets, paired with complementary olive green straight-leg trousers and a soft brown hijab.",
    "A striking cobalt blue co-ord set, including a long-sleeved tunic with a unique side-tie detail and matching palazzo pants. A neutral grey hijab balances the vibrant color.",
    "A cozy yet polished outfit of dark brown corduroy wide-leg trousers paired with a soft, oatmeal-colored long-sleeved Henley top and a matching oatmeal hijab.",
    "A power-casual look with tailored charcoal grey pinstripe trousers and a fitted black long-sleeved top. A sharp black hijab makes the look sleek and professional.",
    "A preppy, layered style with a cream cable-knit sweater vest over a light blue button-up shirt, paired with relaxed-fit ecru trousers and a soft blue hijab.",
    "A sophisticated outfit featuring a long-sleeved blouse with a delicate dark floral print, tucked into flowing black wide-leg culottes. A solid black hijab enhances the elegance.",
    "A sporty luxe combination of deep forest green track pants with a white side stripe, paired with a clean white long-sleeved top and a matching forest green jersey hijab.",
    "A playful matching set in black-and-white gingham, consisting of a long-sleeved top with puff sleeves and a tiered maxi skirt. A classic black hijab ties it all together.",
    "An artistic, layered look with a sleeveless, long black structured tunic over a crisp white shirt, paired with black straight-leg trousers and a contrasting white hijab.",
    "An edgy-chic pairing of black vegan leather trousers with an elegant white long-sleeved blouse featuring delicate lace details at the cuffs, finished with a white silk hijab.",
    "A warm, autumnal palette featuring a burnt orange ribbed top tucked into high-waisted cream wide-leg trousers, complemented by a printed hijab with matching tones.",
    "A comfortable and chic ensemble with a soft grey longline knit cardigan over a white top and light grey straight-leg trousers, paired with a charcoal grey hijab.",
    "A modern bohemian look with a long-sleeved tunic in a subtle sage green and white tie-dye, matched with comfortable white linen-blend trousers and a solid sage green hijab.",
    "A smart outfit composed of high-waisted, wide-leg trousers in a brown and beige check pattern, balanced with a simple fitted black top and a solid black hijab.",
    "A fresh all-white statement look, featuring a textured long-sleeved top and matching white denim culottes, completed with a crisp white hijab for a clean finish.",
    "A polished layered look with a camel-colored sleeveless trench vest, belted over a black long-sleeved top and black wide-leg trousers, with a matching camel hijab.",
    "A subtle print-mixing look with a vertically striped long-sleeve top in blue and white, paired with a floral A-line maxi skirt in a complementary blue palette. A solid navy blue hijab anchors the outfit.",
    "A crinkle-fabric coordinated set in a muted lavender color, featuring a loose-fitting tunic top and comfortable straight-leg trousers, paired with a matching lavender hijab.",
    "A modern kebaya-inspired long outer in a brocade fabric, worn open over a simple cream top and contemporary batik-print palazzo pants, with a simple cream hijab.",
    "A statement tunic with a bold color-block design of half-cream and half-black, paired with sleek black trousers and a black hijab for a graphic look.",
    "A smart casual outfit with a fitted, long-sleeve ribbed top in navy blue, tucked into high-waisted, belted paperbag trousers in a classic camel color, with a navy hijab.",
    "A casual weekend look featuring an oversized, soft fleece half-zip sweatshirt in light grey over a white tee, paired with relaxed-fit black utility cargo pants and a grey jersey hijab.",
    "A strong monochrome statement with an olive green button-down shirt tucked into wide-leg trousers of the exact same shade, paired with a matching olive green silk hijab.",
    "A creative layered look with a long white shirt-dress, belted at the waist and worn open from the waist down, revealing a flowy, light blue pleated maxi skirt underneath, paired with a light blue hijab.",
    "A coordinated beige linen tunic with subtle pleated details, paired with flowing matching wide-leg pants. A soft beige chiffon hijab completes the clean monochrome style.",
  "A soft pastel yellow blouse with balloon sleeves tucked into cream culottes, matched with a pastel yellow chiffon hijab styled simply.",
  "A muted sage green peplum top with ruffled hemline paired with off-white palazzo pants. A soft sage hijab in chiffon fabric ties the look together.",
  "A chic blush pink tunic with a belted waist worn with ivory wide-leg trousers. A satin blush hijab makes the look feminine and graceful.",
  "A stylish earthy brown long overshirt worn open over a cream ribbed top and olive green culottes. A matching earthy brown hijab completes the neutral palette.",
  "A crisp white blouse with puff sleeves tucked into navy culottes, styled with a deep navy satin hijab for a professional vibe.",
  "A lightweight pastel lavender tunic with subtle pleating, paired with soft grey trousers. A lavender chiffon hijab elegantly drapes to match.",
  "A relaxed-fit dusty teal linen tunic with side slits, paired with straight cream trousers. A dusty teal jersey hijab gives a modern minimal look.",
  "A dusty rose satin blouse with bishop sleeves tucked into beige culottes. A matching dusty rose hijab is styled sleekly.",
  "A monochrome taupe look with a long-sleeved tunic and wide-leg pants in matching tones. A silk taupe hijab completes the set.",
  "A contemporary khaki utility tunic with front pockets, paired with cream trousers. A soft khaki hijab ties the earthy palette.",
  "A powder blue asymmetric tunic worn over white culottes, styled with a matching powder blue chiffon hijab.",
  "A deep maroon satin blouse with gathered waist tucked into ivory palazzo pants. A matching maroon chiffon hijab finishes the look.",
  "A chic minimalist look with a long beige sleeveless vest layered over a white blouse and beige trousers. A beige hijab keeps the monochrome balance.",
  "A fresh mint green blouse with pleated sleeves tucked into white culottes. A mint satin hijab complements the outfit perfectly.",
  "A warm autumn palette with a rust-orange blouse tucked into cream linen trousers. A rust hijab adds harmony.",
  "A sleek navy button-down tunic paired with matching navy wide trousers. A slightly lighter navy hijab provides tonal layering.",
  "A feminine soft peach blouse with a tie-neck detail paired with ivory culottes. A matching peach chiffon hijab completes the style.",
  "A moss green long tunic with belt detail, paired with ecru wide trousers. A moss green hijab balances the look.",
  "A beige pleated blouse tucked into soft brown culottes. A beige chiffon hijab keeps the muted tones consistent.",
  "A soft lilac satin top with bishop sleeves tucked into cream trousers. A lilac hijab adds elegance.",
  "A minimalist monochrome grey set with a long grey tunic and culottes. A silk grey hijab drapes simply.",
  "A dusty coral belted tunic paired with ivory trousers. A matching coral hijab styled loosely frames the face.",
  "A soft olive blouse with subtle embroidery paired with beige culottes. An olive chiffon hijab completes the earthy balance.",
  "A blush satin tunic with balloon sleeves, worn with ivory culottes. A blush pink hijab enhances the soft palette.",
  "A classic navy peplum blouse with ruffle hem paired with white trousers. A navy chiffon hijab makes it polished.",
  "A pastel pistachio blouse with tie waist paired with off-white culottes. A pistachio hijab draped elegantly matches perfectly.",
  "A muted terracotta tunic with subtle pleats paired with beige palazzo pants. A terracotta hijab styled loosely keeps it chic.",
  "A monochrome sand beige look with tunic and wide pants in the same tone. A silk sand hijab enhances the minimal look.",
  "A dusty lavender blouse with gathered neckline tucked into cream trousers. A lavender hijab styled sleekly completes the feminine look.",
  "A deep forest green satin blouse with bishop sleeves tucked into ivory culottes. A forest green hijab matches elegantly.",
  "A light khaki tunic with asymmetric hemline paired with cream trousers. A khaki chiffon hijab flows seamlessly.",
  "A pastel baby blue blouse tucked into white culottes. A baby blue hijab completes the soft palette.",
  "A deep plum blouse with subtle satin shine paired with beige culottes. A plum chiffon hijab harmonizes the look.",
  "A soft cream blouse with lace trim paired with taupe culottes. A cream hijab keeps the outfit light and clean.",
  "A muted olive-green tunic with tie belt detail paired with ivory trousers. A matching olive hijab balances the tone.",
  "A dusty rose long overshirt layered over a cream top and trousers. A dusty rose hijab gives tonal consistency.",
  "A chic monochrome charcoal grey blouse and culotte pairing, styled with a silk charcoal hijab.",
  "A pastel yellow tunic with soft gathers at the waist, paired with white culottes. A pastel yellow chiffon hijab enhances the cheerful vibe.",
  "A muted mocha blouse with subtle puff sleeves tucked into cream trousers. A mocha hijab complements the earthy tones.",
  "A soft teal blouse with pleated neckline paired with beige culottes. A matching teal hijab styled simply completes the look.",
  "A powder pink blouse with tie waist paired with ivory trousers. A matching pink hijab gives a sweet pastel look.",
  "A sophisticated navy tunic with belted waist paired with taupe trousers. A navy chiffon hijab finishes it elegantly.",
  "A creamy ivory blouse with subtle embroidery tucked into camel culottes. A matching ivory hijab balances the neutral palette.",
  "A deep wine red blouse paired with soft beige trousers. A matching wine chiffon hijab adds richness.",
  "A soft sage green longline vest layered over a white blouse and trousers. A sage hijab ties the monochrome look.",
  "A chic grey blouse with balloon sleeves tucked into ivory culottes. A soft grey hijab styled neatly complements the palette.",
  "A dusty peach blouse with subtle shine tucked into cream trousers. A peach chiffon hijab completes the tone.",
  "A muted lilac blouse with pleated neckline paired with off-white culottes. A lilac hijab styled simply matches the outfit."

];

export const femaleClothingNoHijab = [
  // Elegant & Flowy
  "A soft blush pink wide-leg jumpsuit with a V-neckline, subtle ruffles on the shoulders, and a self-tie belt at the waist. She wears delicate gold hoop earrings and nude block heels.",
  "An ivory linen palazzo pants paired with a matching structured peplum top, featuring a square neckline and puff sleeves. Accessorized with layered gold necklaces and pointed-toe flats.",
  "A flowing periwinkle blue wide-leg trousers and a coordinating sleeveless top with an asymmetrical hem. Styled with silver minimalist jewelry and white leather mules.",
  "A cream-colored satin wide-leg pants and a draped off-the-shoulder blouse. She wears a statement pearl necklace and open-toe heels.",
  "A light olive green high-waisted culottes paired with a fitted wrap-around top, showcasing a delicate floral print. Finished with simple stud earrings and espadrille wedges.",
  "A navy blue silk wide-leg jumpsuit with a keyhole cutout at the back and a high neck. Accessorized with a stack of thin bangles and metallic sandals.",
  "A terracotta-colored flowy palazzo pants with a matching long-sleeve crop top, featuring intricate embroidery on the cuffs. She wears large hoop earrings and woven sandals.",
  "A sage green linen wide-leg trousers and a simple white camisole, layered with an open-front longline cardigan. Styled with a delicate pendant necklace and white sneakers.",
  "A charcoal grey pleated wide-leg pants and a loose-fitting ivory turtleneck sweater. Accessorized with a structured tote bag and ankle boots.",
  "A muted gold wide-leg satin trousers paired with an elegant one-shoulder top. She wears delicate drop earrings and clear strap heels.",

  // Modern & Chic
  "A tailored forest green straight-leg trousers with a high waist, paired with a white oversized button-down shirt, partially tucked in. Accessorized with a statement belt and black loafers.",
  "A sleek black cigarette pants and a cream long-sleeve knit top with a boat neck. She wears a minimalist watch and small diamond earrings.",
  "A vibrant cobalt blue tailored trousers and a white structured blouse with balloon sleeves. Styled with a bold red lip and pointed-toe pumps.",
  "A camel-colored high-waisted trousers with a slight flare at the ankle, paired with a fitted black long-sleeve top. Accessorized with a gold chain necklace and black ankle boots.",
  "An emerald green slim-fit trousers and a simple white tee, layered under a tweed blazer. She carries a structured mini bag and wears white sneakers.",
  "A deep burgundy tailored trousers and a contrasting light grey cashmere sweater. Styled with a delicate silver bracelet and patent leather flats.",
  "A classic plaid straight-leg pants in muted tones, paired with a black mock-neck top. Accessorized with small hoop earrings and Chelsea boots.",
  "A pristine white tailored trousers and a soft pastel yellow knit top with a ribbed texture. She wears a simple gold ring and nude mules.",
  "A charcoal grey wide-leg trousers and a black satin camisole, layered with an oversized blazer. Styled with a delicate lariat necklace and black stiletto heels.",
  "A mocha brown corduroy trousers with a straight leg, paired with a cream knitted vest over a white long-sleeve shirt. She wears round glasses and brown loafers.",

  // Relaxed & Bohemian
  "An earthy toned striped linen wide-leg trousers and a white loose-fitting off-the-shoulder top with puff sleeves. She wears stacked beaded bracelets and flat leather sandals.",
  "A rust-colored flowy harem pants and an ivory embroidered peasant blouse. Accessorized with a delicate headpiece and woven sandals.",
  "A cream linen blend wide-leg pants and a matching loose-fitting tunic top with side slits. She wears a long pendant necklace and espadrille flats.",
  "A light denim blue wide-leg jeans with a distressed hem, paired with a white flowy bohemian top with bell sleeves. Styled with a fringed cross-body bag and suede ankle boots.",
  "A patterned palazzo pants in warm, muted tones (e.g., paisley or floral) and a simple white tank top, layered with a kimono-style cardigan. She wears large hoop earrings and platform sandals.",
  "A forest green linen overalls with a wide-leg cut, worn over a white long-sleeve top. Accessorized with a canvas tote bag and white sneakers.",
  "A loose-fitting cream cotton trousers with an elasticated waist, paired with a matching short-sleeve button-down shirt, tied at the waist. She wears a straw hat and bare feet.",
  "A burnt orange culottes in a soft fabric and an off-white smocked top. Styled with chunky wooden bangles and leather slides.",
  "A black flowy trousers with a subtle ethnic print and a white oversized t-shirt, tied at the side. She wears layered necklaces and simple black sandals.",
  "A soft grey wide-leg lounge pants and an ivory oversized knit sweater. Accessorized with a chunky scarf and comfortable Ugg boots (for cozy prewedding shoots).",

  // Modern Romance
  "A light grey high-waisted trousers with a gentle flare, paired with a sheer lace top in the same shade, layered over a nude camisole. She wears delicate silver jewelry and nude heels.",
  "A dusty rose tailored cigarette pants and a white silk camisole, layered under a long, flowy sheer organza jacket. Styled with pearl drop earrings and silver strappy sandals.",
  "An ivory wide-leg crepe jumpsuit with a sweetheart neckline and delicate spaghetti straps. She wears a diamond pendant necklace and blush pink pumps.",
  "A champagne-colored satin wide-leg trousers and a matching long-sleeve blouse with a keyhole detail at the back. Accessorized with a statement hair clip and soft waves.",
  "A powder blue palazzo pants and a white off-the-shoulder top with intricate lace detailing. She wears a delicate gold bracelet and white block heels.",
  "A soft lavender high-waisted trousers and an ivory wrap top with a deep V-neckline and voluminous sleeves. Styled with a delicate floral hair accessory and bare feet for a romantic outdoor shoot.",
  "A cream tailored trousers with a straight leg, paired with a blush pink satin cowl-neck top. She wears a string of pearls and pointed-toe flats.",
  "A mint green wide-leg jumpsuit with a delicate lace overlay on the bodice. Accessorized with small diamond stud earrings and nude platform sandals.",
  "A soft peach high-waisted trousers and an ivory long-sleeve top with subtle ruffles on the shoulders. Styled with a delicate gold chain necklace and blush pink mules.",
  "A light silver grey cigarette pants and a white elegant halter-neck top. She wears minimalist silver jewelry and white strappy heels.",

  // Bold & Playful
  "A vibrant fuchsia pink tailored wide-leg trousers and a simple white fitted tank top. Accessorized with oversized gold hoop earrings and white sneakers.",
  "A bright sunshine yellow palazzo pants and a white cropped bustier top, layered with an open denim jacket. She wears colorful beaded jewelry and platform sandals.",
  "A bold floral print wide-leg trousers (e.g., large hibiscus or tropical leaves) and a solid white off-the-shoulder crop top. Styled with a straw hat and wedges.",
  "A cherry red tailored trousers and a black long-sleeve mesh top layered over a black bralette. She wears a statement silver choker and black combat boots for an edgy look.",
  "A leopard print wide-leg pants and a black oversized t-shirt, tied at the waist. Accessorized with large gold hoop earrings and black chunky sneakers.",
  "A royal blue tailored jumpsuit with a playful cutout detail at the waist and a wide leg. She wears a bold red lipstick and silver pointed-toe heels.",
  "A bright orange high-waisted trousers and a white asymmetrical one-shoulder top. Styled with layered gold necklaces and nude strappy sandals.",
  "A neon green wide-leg pants and a simple black sleeveless crop top. Accessorized with chunky silver jewelry and black platform boots.",
  "A striped wide-leg pants (e.g., vertical black and white) and a black fitted long-sleeve top. She wears oversized sunglasses and red Converse sneakers.",
  "A metallic silver tailored trousers and a black sequined crop top, layered with a black leather jacket. Styled with smokey eye makeup and black ankle boots.",

  // Cozy & Intimate
  "A cream knitted wide-leg lounge pants and a matching oversized knitted sweater. She wears fluffy socks and holds a mug of coffee.",
  "A soft grey cotton joggers and a white oversized t-shirt, partially tucked in. She wears a messy bun and bare feet.",
  "A light blue denim overalls with a relaxed fit, worn over a white long-sleeve thermal top. Accessorized with a beanie hat and white sneakers.",
  "A comfortable black ribbed knit trousers and an oversized white button-down shirt, unbuttoned over a simple black tank top. She wears a delicate necklace and soft hair.",
  "A warm mustard yellow wide-leg lounge pants and a white cropped hoodie. Styled with chunky knit socks and a relaxed pose.",
  "A muted pink high-waisted wide-leg trousers in a brushed fabric and a white slouchy off-the-shoulder sweater. She wears delicate stud earrings and a relaxed hairstyle.",
  "A dark green velvet wide-leg lounge pants and an ivory long-sleeve top with a cowl neck. She wears cozy slippers and is wrapped in a soft blanket.",
  "A beige linen blend wide-leg trousers and a simple white tank top, layered with an open-front longline cardigan. She wears minimal makeup and a natural hairstyle.",
  "A charcoal grey knitted wide-leg pants and a white long-sleeve thermal top, layered with a chunky knit cardigan. She wears a messy bun and warm socks.",
  "A soft purple wide-leg lounge pants and a white oversized t-shirt, styled with a half-tuck. She wears a delicate silver necklace and a relaxed, cozy expression.",

  // Unique Textures & Details
  "A black faux leather wide-leg trousers and a crisp white button-down shirt with oversized cuffs. Accessorized with a statement belt and black pointed-toe boots.",
  "An ivory embroidered wide-leg trousers with intricate floral patterns, paired with a simple white fitted sleeveless top. She wears delicate gold jewelry and nude sandals.",
  "A navy blue velvet palazzo pants and a matching sleeveless top with a high neck. Styled with sparkling drop earrings and silver heels.",
  "A light denim blue wide-leg jeans with unique patchwork details, paired with a white off-the-shoulder top with smocking. She wears wooden bangles and espadrille wedges.",
  "A deep burgundy lace wide-leg trousers (lined appropriately) and a black satin camisole. Accessorized with a statement necklace and black heels.",
  "A white textured wide-leg pants (e.g., broderie anglaise or eyelet fabric) and a simple white ribbed tank top. She wears a straw hat and bare feet for a beachy vibe.",
  "A champagne-colored sequined wide-leg trousers and a white oversized t-shirt, tied at the waist. Styled with minimalist silver jewelry and white sneakers.",
  "A forest green corduroy wide-leg trousers and a cream cable-knit sweater. She wears a delicate pendant necklace and brown loafers.",
  "A black wide-leg trousers with subtle pinstripes and a white silk blouse with a pussy-bow tie. Accessorized with pearl earrings and black pumps.",
  "An olive green utilitarian-style wide-leg trousers with cargo pockets, paired with a fitted black long-sleeve top. She wears a minimalist silver necklace and combat boots.",
];


export const adatInspirations = [
  // Jawa
  {
    region: "Jawa Tengah & Yogyakarta",
    groom: "Javanese groom in a traditional Beskap landung jacket, often in a dark color like black or navy, with intricate gold embroidery, paired with a batik jarik cloth wrapped around the waist, and a Blangkon on his head.",
    groom_id: "Beskap dengan Batik Jarik dan Blangkon",
    bride_hijab: "Javanese bride in a modern, elegant kebaya made of velvet or brocade, paired with a matching batik jarik. For the hijab style, she wears a graceful 'Paes Ageng' inspired look where the hijab is styled neatly under intricate head decorations and a 'cunduk mentul' hairpin arrangement.",
    bride_hijab_id: "Paes Ageng (Hijab)",
    bride_nonhijab: "Javanese bride in a classic velvet or brocade kebaya with a matching batik jarik. Her hair is styled in a traditional 'sanggul' bun, adorned with the intricate 'Paes Ageng' makeup and a 'cunduk mentul' hairpin arrangement.",
    bride_nonhijab_id: "Paes Ageng (Sanggul)"
  },
  {
    region: "Sunda (Jawa Barat)",
    groom: "Sundanese groom wearing an elegant Beskap Sunda, often in white or a light color, with a 'Bendo' head covering, and a batik cloth as the lower garment.",
    groom_id: "Beskap Sunda dengan Bendo",
    bride_hijab: "Sundanese bride in an elegant long-sleeved Kebaya Sunda, typically made of brocade, paired with a matching hijab styled beautifully under the iconic 'Siger Sunda' crown.",
    bride_hijab_id: "Kebaya dengan Siger Sunda (Hijab)",
    bride_nonhijab: "Sundanese bride in a classic brocade Kebaya Sunda with her hair styled in a traditional 'sanggul' and adorned with the magnificent 'Siger Sunda' crown.",
    bride_nonhijab_id: "Kebaya dengan Siger Sunda (Sanggul)"
  },
  // Sumatra
  {
    region: "Minangkabau (Sumatera Barat)",
    groom: "Minang groom in Baju Gadang with Songket trousers and Saluak headcover.",
    groom_id: "Baju Gadang dan Saluak",
    bride_hijab: "Minang bride in a richly embroidered Baju Kurung with golden threads, with a hijab styled to fit under the iconic, towering golden Suntiang headpiece.",
    bride_hijab_id: "Baju Kurung dengan Suntiang (Hijab)",
    bride_nonhijab: "Minang bride in a richly embroidered Baju Kurung with golden threads, wearing a towering golden Suntiang headpiece over her traditionally styled hair.",
    bride_nonhijab_id: "Baju Kurung dengan Suntiang (Sanggul)"
  },
  {
    region: "Palembang (Sumatera Selatan)",
    groom: "Palembang groom in Aesan Paksangko attire with intricate gold embroidery and crown.",
    groom_id: "Aesan Paksangko",
    bride_hijab: "Palembang bride in Aesan Gede attire, with a hijab neatly styled under a magnificent golden crown and elaborate jewelry.",
    bride_hijab_id: "Aesan Gede (Hijab)",
    bride_nonhijab: "Palembang bride in Aesan Gede attire with a golden crown over her traditionally styled hair and elaborate jewelry.",
    bride_nonhijab_id: "Aesan Gede (Sanggul)"
  },
  {
    region: "Aceh",
    groom: "Aceh groom in Linto Baro attire with a Kupiah Meukeutop headpiece.",
    groom_id: "Linto Baro dengan Kupiah Meukeutop",
    bride_hijab: "Aceh bride in Daro Baro attire, featuring a hijab styled gracefully with a veil and intricate golden jewelry.",
    bride_hijab_id: "Daro Baro (Hijab)",
    bride_nonhijab: "Aceh bride in Daro Baro attire, adorned with a veil and intricate golden jewelry over her traditionally styled hair.",
    bride_nonhijab_id: "Daro Baro (Sanggul)"
  },
  {
    region: "Batak Toba (Sumatera Utara)",
    groom: "Batak Toba groom in traditional black attire with a Bulang crown, and a traditional Ulos cloth draped over his shoulder.",
    groom_id: "Pakaian Hitam dengan Mahkota Bulang dan Ulos",
    bride_hijab: "Batak Toba bride in a modern kebaya paired with an Ulos cloth. Her hijab is styled to fit under a traditional Batak headpiece ('sortali').",
    bride_hijab_id: "Kebaya dengan Ulos dan Sortali (Hijab)",
    bride_nonhijab: "Batak Toba bride in a kebaya with an Ulos cloth, her hair styled in a bun and adorned with a traditional headscarf or 'sortali' accessories.",
    bride_nonhijab_id: "Kebaya dengan Ulos dan Sortali (Sanggul)"
  },
  {
    region: "Melayu Riau",
    groom: "Malay groom in Teluk Belanga attire with a songket sarong wrapped at the waist and a tanjak headdress.",
    groom_id: "Teluk Belanga dengan Tanjak",
    bride_hijab: "Malay bride in an elegant Baju Kurung Melayu made of fine songket, with a hijab styled gracefully under a veil and delicate tiara.",
    bride_hijab_id: "Baju Kurung dengan Tiara (Hijab)",
    bride_nonhijab: "Malay bride in a Baju Kurung Melayu with a veil and fine songket, her hair styled in a bun with traditional jewelry.",
    bride_nonhijab_id: "Baju Kurung (Sanggul)"
  },
  {
    region: "Lampung",
    groom: "Groom in traditional Lampung attire featuring Tumpal motifs and a kopiah emas (golden cap).",
    groom_id: "Pakaian Adat Lampung dengan Kopiah Emas",
    bride_hijab: "Lampung bride wearing Songket Lampung, with a hijab styled to fit perfectly under the large, iconic golden Siger crown.",
    bride_hijab_id: "Songket dengan Siger (Hijab)",
    bride_nonhijab: "Lampung bride wearing Songket Lampung with her hair styled traditionally under a large, iconic golden Siger crown.",
    bride_nonhijab_id: "Songket dengan Siger (Sanggul)"
  },
  // Bali & Nusa Tenggara
  {
    region: "Bali",
    groom: "Balinese groom in 'Payas Agung' style, wearing a white Balinese shirt, an 'udeng' headpiece, and a Kamen cloth, often with a Keris.",
    groom_id: "Payas Agung Pria (dengan Udeng)",
    bride_hijab: "Balinese bride in a 'Payas Agung' style, adapted for hijab. She wears a beautiful wrapped cloth around her body with a hijab styled neatly to accommodate the towering, golden flower crown.",
    bride_hijab_id: "Payas Agung (Hijab)",
    bride_nonhijab: "Balinese bride in the 'Payas Agung' style, with her hair elaborately styled and adorned with a towering golden flower crown.",
    bride_nonhijab_id: "Payas Agung (Sanggul)"
  },
  {
    region: "Sasak (Lombok, NTB)",
    groom: "Sasak groom in Pegon attire with a Songket sarong and Sapuk headpiece.",
    groom_id: "Pakaian Pegon dengan Sapuk",
    bride_hijab: "Sasak bride wearing a Lambung blouse, adapted with long sleeves, paired with a Songket Lombok cloth and a simple, matching hijab.",
    bride_hijab_id: "Baju Lambung (Hijab)",
    bride_nonhijab: "Sasak bride wearing a traditional Lambung blouse with a Songket Lombok cloth, hair styled in a bun.",
    bride_nonhijab_id: "Baju Lambung (Sanggul)"
  },
  {
    region: "Sumba (NTT)",
    groom: "Sumba groom wearing a traditional Hinggi Kawuru ikat cloth with a decorative headpiece (Tiara Patang).",
    groom_id: "Kain Hinggi dengan Tiara Patang",
    bride_hijab: "Sumba bride wearing a Lawo Lambaleko cloth adapted into a modest dress, with a simple hijab and traditional Sumba jewelry (Mamuli).",
    bride_hijab_id: "Lawo Lambaleko (Hijab)",
    bride_nonhijab: "Sumba bride wearing a Lawo Lambaleko cloth, adorned with elaborate traditional jewelry like the Mamuli earrings and a headpiece.",
    bride_nonhijab_id: "Lawo Lambaleko (Sanggul)"
  },
  // Kalimantan
  {
    region: "Dayak (Kalimantan)",
    groom: "Dayak groom in a traditional vest made of bark or animal skin, with an Enggang (hornbill) feather headpiece.",
    groom_id: "Rompi Dayak dengan Hiasan Kepala Enggang",
    bride_hijab: "Dayak bride in a modern interpretation of Baju Manik (beaded dress) with long sleeves, paired with a simple hijab adorned with a single Enggang feather.",
    bride_hijab_id: "Baju Manik (Hijab)",
    bride_nonhijab: "Dayak bride wearing a Baju Manik (beaded dress) with an Enggang (hornbill) feather crown.",
    bride_nonhijab_id: "Baju Manik (Sanggul)"
  },
  {
    region: "Banjar (Kalimantan Selatan)",
    groom: "Banjar groom in traditional attire with rich gold embroidery and a tall hat.",
    groom_id: "Pakaian Banjar Pria",
    bride_hijab: "Banjar bride in 'Pengantin Baamar Galung' attire, with a hijab styled neatly under the magnificent golden crown.",
    bride_hijab_id: "Baamar Galung (Hijab)",
    bride_nonhijab: "Banjar bride in 'Pengantin Baamar Galung' attire with a magnificent golden crown over her traditionally styled hair.",
    bride_nonhijab_id: "Baamar Galung (Sanggul)"
  },
  // Sulawesi
  {
    region: "Bugis (Sulawesi Selatan)",
    groom: "Bugis groom in a 'Jas Tutu' (closed-collar jacket) with a Passapu headcloth and a 'lipa sabbe' silk sarong.",
    groom_id: "Jas Tutu dengan Passapu",
    bride_hijab: "Bugis bride in a vibrant, square-cut 'Baju Bodo' top made of semi-transparent fabric, worn over a long-sleeved inner shirt and a silk 'lipa sabbe' sarong. Her hijab is styled simply to complement the colorful outfit and traditional jewelry.",
    bride_hijab_id: "Baju Bodo (Hijab)",
    bride_nonhijab: "Bugis bride in a vibrant, square-cut 'Baju Bodo' top, paired with a silk 'lipa sabbe' sarong, with her hair in an intricate bun adorned with golden accessories.",
    bride_nonhijab_id: "Baju Bodo (Sanggul)"
  },
  {
    region: "Makassar (Sulawesi Selatan)",
    groom: "Makassar groom in a 'Jas Tutu' with a Songket sarong.",
    groom_id: "Jas Tutu Makassar",
    bride_hijab: "Makassar bride in a Baju Bodo over a long-sleeved inner shirt, with a simple hijab and layered, intricate jewelry.",
    bride_hijab_id: "Baju Bodo Makassar (Hijab)",
    bride_nonhijab: "Makassar bride in a Baju Bodo with layered, intricate jewelry and her hair in a traditional bun.",
    bride_nonhijab_id: "Baju Bodo Makassar (Sanggul)"
  },
  {
    region: "Toraja (Sulawesi Selatan)",
    groom: "Toraja groom in 'Seppa Tallu Buku' trousers with a Passapu headpiece.",
    groom_id: "Seppa Tallu Buku dengan Passapu",
    bride_hijab: "Toraja bride in a long-sleeved 'Pokko' blouse with a simple hijab, adorned with a traditional Toraja bead crown ('Kandaure').",
    bride_hijab_id: "Baju Pokko' dengan Kandaure (Hijab)",
    bride_nonhijab: "Toraja bride in a 'Pokko' blouse with a traditional Toraja bead crown ('Kandaure') over her hair.",
    bride_nonhijab_id: "Baju Pokko' dengan Kandaure (Sanggul)"
  },
  {
    region: "Gorontalo",
    groom: "Gorontalo groom in 'Makuta' attire with a crown.",
    groom_id: "Pakaian Makuta",
    bride_hijab: "Gorontalo bride in 'Biliu' attire, with a hijab styled to fit under the veil and elaborate headpiece.",
    bride_hijab_id: "Pakaian Biliu (Hijab)",
    bride_nonhijab: "Gorontalo bride in 'Biliu' attire with a veil and elaborate headpiece over her hair.",
    bride_nonhijab_id: "Pakaian Biliu (Sanggul)"
  },
  // Maluku & Papua
  {
    region: "Maluku Tengah",
    groom: "Maluku groom in a Baju Cele (red striped shirt) with a matching sarong and a red headband.",
    groom_id: "Baju Cele Pria",
    bride_hijab: "Maluku bride in a modern Baju Cele with long sleeves and a matching red or white hijab, adorned with golden jewelry.",
    bride_hijab_id: "Baju Cele (Hijab)",
    bride_nonhijab: "Maluku bride in a traditional Baju Cele (red striped dress) with golden jewelry and hair accessories.",
    bride_nonhijab_id: "Baju Cele (Sanggul)"
  },
  {
    region: "Papua",
    groom: "Papua groom with a traditional feather headdress, Noken bag, and traditional body paint.",
    groom_id: "Pakaian Adat Pria Papua",
    bride_hijab: "A modern, modest interpretation of Papuan attire, using natural fabrics and beadwork, with a simple head covering and shell necklace.",
    bride_hijab_id: "Pakaian Adat Wanita Papua (Hijab)",
    bride_nonhijab: "Papua bride wearing a 'rok rumbai' (grass skirt) with a shell necklace, Noken bag, and feather adornments.",
    bride_nonhijab_id: "Rok Rumbai dan Hiasan Kepala"
  }
];

export const negativePromptOptions = [

'Deformed Hand',
'Deformed Finger',
'Deformed Face',
'Text/Watermark',
'Blurry',
'Kiss',
'Odd Proportions',
'Bad Lighting',
];

export const loadingScreenTips = [
    "AI sedang meracik setiap detail, mulai dari pencahayaan sinematik hingga ekspresi yang tulus...",
    "Setiap foto adalah mahakarya baru. AI kami sedang melukis dengan cahaya dan emosi untuk Anda.",
    "Sabar sebentar... Keajaiban sedang dalam proses. Kami sedang menciptakan kenangan yang tak terlupakan.",
    "Dari jutaan kemungkinan, AI sedang memilih pose, latar, dan suasana yang paling sempurna untuk Anda.",
    "Fotografer AI kami sedang menyesuaikan lensanya untuk menangkap koneksi tulus antara Anda berdua.",
    "Sedang membangun dunia impian Anda, piksel demi piksel. Hasil yang menakjubkan akan segera tiba.",
    "Analisis gaya, pencocokan warna, dan penyusunan komposisi... Detail sempurna butuh sedikit waktu.",
    "Harap tunggu, kami sedang menyelaraskan algoritma kreativitas untuk hasil yang melebihi ekspektasi.",
    "Fotografer tidak pernah tidur. AI kami bekerja keras 24/7 untuk menciptakan foto prewedding impian Anda.",
    "Menerjemahkan prompt Anda menjadi sebuah mahakarya visual. Proses artistik ini sedang berlangsung."
];